#!/bin/bash

echo "starting script"

debug="false"
silenterr=" 2>/dev/null "
silent=" >/dev/null 2>&1 "
silentvpn=" 2>/dev/null "
if [[ "$1" == "--debug" ]];
then
	silenterr=""
	silent=""
	silentvpn=" | tee /var/log/openvpn.log"
	debug="true";
fi
dbg() {
	if [[ $debug == "true" ]];
	then
		echo $@ >&2
	fi
}

dbg "checking dependencies"
dependencies="route grep awk head kill pkill openvpn ifconfig tshark script xxd socat"
for dep in $dependencies;
do
	if ! command -v "${dep}" >/dev/null;
	then
		echo "please install ${dep}" >&2
		exit 1
	fi
done
dbg "dependencies checked"

dbg "check for permissions (root)"
if [[ "$EUID" -ne 0 ]];
then
	echo "please run as root (e.g. sudo)" >&2;
	exit 2;
fi
dbg "checked for permissions"

dbg "setting default interface"
# will be your default wifi/ethernet device
# I did not yet test this with multiple interfaces,
DEFAULT_INTERFACE=$(/sbin/route 2>/dev/null | grep '\b0.0.0.0\b' | awk '{print $8}' | head -n1)
# probably no need to change this
STEAM_PORT=27036
dbg "default interface set to $DEFAULT_INTERFACE"

# first we kill all the processes we started
# we then use the exit command we all know and love <3
exit() {
	echo -n "cleaning up..."
	sudo kill $(cat /var/run/openvpn.pid) 2>/dev/null
	sudo pkill -P $(cat /var/run/openvpnup.pid)
	echo "done"
	builtin exit $1
}

trap exit 1 2 3 15

dbg "starting openvpn"

openvpn --config /etc/openvpn/client.ovpn --askpass /etc/openvpn/pass >/var/log/openvpn.log $silentvpn &
echo $! > /var/run/openvpn.pid
dbg "openvpn started with pid: $(cat /var/run/openvpn.pid)"
dbg "waiting for vpn connection"

i=0
while ! grep 'Initialization Sequence Completed' /var/log/openvpn.log;
do
	sleep 0.2
	((i++))
	# abort if it takes 20s
	if [[ $i -gt 100 ]];
	then
		exit 3
	fi
done
dbg "vpn connection established"

dbg "finding tap interface"
# will most likely be "tap0"
TAP_INTERFACE=$(ifconfig | grep tap | awk '{print $1}')
dbg "tap interface set to $TAP_INTERFACE"



dbg "starting broadcast packet capture"
# we use:
#   tshark to capture the broadcast packets which are used by steam to detect in-home streamers
#   xxd to transform the captured hexdecimal packets into binary
#   socat to relay the broadcast to the vpn server over the tap interface
bash -c "tshark -i ${DEFAULT_INTERFACE} -T fields -e data -l 'udp and dst port ${STEAM_PORT}' $silenterr \
	| script -q /dev/null -c 'xxd -r -p' $silenterr \
	| socat - UDP-DATAGRAM:10.8.0.1:${STEAM_PORT},broadcast,so-bindtodevice=${TAP_INTERFACE} $silenterr \
	"&

echo $! > /var/run/openvpnup.pid
dbg "packet capture started with pid: $(cat /var/run/openvpnup.pid)"

echo "script finished, shut down with Ctrl+C"
wait
